apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: masselli/meubanco:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3305

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
    - port: 3305
  selector:
    app: mysql
  clusterIP: None
