apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
spec:
  containers:
    - name: mysql-pod
      image: mysql:latest
      env:
        - name: "MYSQL_DATABASE"
          value: "meubanco"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "12"
      ports:
        - containerPort: 3305
